dist: xenial
language: python
cache: pip

matrix:
  include:
    - python: "3.7"
      env: PYTHONVER=3

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphviz
  homebrew:
    update: true
    packages:
      - python
      - graphviz

branches:
  only:
  - master

install: 
  - python3 -m pip install -e .[dev]

script: 
  - make lint
  - make tests

after_success: 
  - python3 -m codecov --token 3fe34ae3-3af3-4c6f-acb8-97b1d0334bff

notifications:
  email: false
