language: python
cache: pip

matrix:
  include:
    - python: "2.7"
      env: PYTHONVER=2
    - python: "3.6"
      env: PYTHONVER=3

branches:
  only:
  - master

install: 
  - if [ "$PYTHONVER" = "2" ]; then python2 -m pip install -r requirements_py2.txt && python2 -m pip install -U pytest pytest-cov flake8 pylint codecov; fi
  - if [ "$PYTHONVER" = "3" ]; then python3 -m pip install -r requirements.txt && python3 -m pip install -U pytest pytest-cov flake8 pylint codecov; fi

script: 
  # - if [ "$PYTHONVER" = "2" ]; then echo "Python2" && make testpy2; fi
  - if [ "$PYTHONVER" = "3" ]; then echo "Python3" && make test; fi
  - echo $PYTHONVER

after_success: 
  - if [ "$PYTHONVER" = "3" ]; then python3 -m codecov --token 3fe34ae3-3af3-4c6f-acb8-97b1d0334bff; fi

notifications:
  email: false
